CREATE TABLE MEDICO (
	CPF INTEGER PRIMARY KEY,
  	CRM VARCHAR(16),
  	TELEFONE1 INTEGER,
  	TELEFONE2 INTEGER,
  	NOME VARCHAR(128),
  	EMAIL1 VARCHAR(64),
  	EMAIL2 VARCHAR(64)
);

CREATE TABLE POSTO(
	ID INTEGER PRIMARY KEY,
  	LOCALIZACAO VARCHAR(128),
  	NOME VARCHAR(128)
);

CREATE TABLE PACIENTE (
    CPF INTEGER PRIMARY KEY,
    TELEFONE1 INTEGER,
    TELEFONE2 INTEGER,
    NOME VARCHAR(128),
    EMAIL1 VARCHAR(64),
    EMAIL2 VARCHAR(64),
  	POSTO_CADASTRADO INTEGER,
  	FOREIGN KEY (posto_cadastrado) rEFERENCES POSTO(ID)
);

CREATE TABLE CADASTRO_MEDICO (
	CPF_MEDICO INTEGER,
  	ID_POSTO INTEGER PRIMARY KEY,
  	FOREIGN KEY(CPF_MEDICO) REFERENCES MEDICO(CPF),
  	FOREIGN KEY(ID_POSTO) REFERENCES POSTO(ID)
);

CREATE TABLE CONSULTA (
	ID_MEDICO INTEGER,
  	ID_PACIENTE INTEGER,
  	DATA DATE,
  	TIPO VARCHAR(32),
  	HORARIO TIME,
  	PRIMARY KEY(ID_MEDICO, ID_PACIENTE),
  	FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(CPF),
  	FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE DOCUMENTO(
  	ID INTEGER PRIMARY KEY,
	ID_MEDICO INTEGER,
  	ID_PACIENTE INTEGER,
  	TIPO VARCHAR(64),
  	NOME VARCHAR(64),
  	ID_CONSULTA INTEGER,
  	FOREIGN KEY(ID_MEDICO, ID_PACIENTE) REFERENCES CONSULTA(ID_MEDICO, ID_PACIENTE)
);
